version: '3.1'

services:
  api:
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - dbmysql
      - dbmongo

  dbmysql:
    build:
      context: ./databases/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - "3306:3306"
    volumes:
      - './data_sql_db:/data/db'

  dbmongo:
    build:
      context: ./databases/mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - './data_nosql_db:/data/db'
