version: '3.1'

services:

  # api:
  #   build: .
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - database-mysql
  #     - database-mongo

  database-mysql:
    build:
      context: ./databases/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - "3306:3306"
    volumes:
      - './data_sql_db:/data/db'
  # database-mongo:
  #   build:
  #     context: ./databases/mongodb
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - './data_nosql_db:/data/db'
